### PR TITLE
Allow to change host server and clean build directory at each build

### PR DESCRIPTION
**Pull request by prkumar**

### CODE REVIEW

**Comment by prkumar** [comment]
@Shir0kamii - Hey! I found your change to allow configuration of host server (through the Networks tab under Insights) and thought it would be a cool addition to the mainline. Would it be OK for me to merge your fork on your behalf? No worries if you'd prefer not :)

**Comment by prkumar** [comment]
Should fix #5 

CC: @naftulikay

**Comment by Shir0kamii** [comment]
Hi! Sure you can!

**Comment by prkumar** [comment]
@Shir0kamii - Awesome! 😃 I'll resolve the conflicts and merge the fix later tonight. Thank you!

**Pull request merged**
